=== LCSB-BioCore/frog-specification/schema/frog-metadata-v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://identifiers.org/combine.specifications:frog-metadata-schema-v1",
  "title": "FROG Metadata",
  "description": "Schema of the JSON metadata file to be used in the FROG reports",
  "type": "object",
  "properties": {
    "frog_version": {
      "type": "string",
      "description": "version of the FROG standard"
    },
    "model_filename": {
      "type": "string",
      "description": "name of the file described by the report"
    },
    "model_md5": {
      "type": "string",
      "description": "hex-encoded MD5 hash of the model file"
    },
    "model_sha256": {
      "type": "string",
      "description": "hex-encoded SHA256 hash of the model file"
    },
    "model_file_url": {
      "type": "string",
      "description": "URL from where model file can be obtained"
    },
    "model_development_url": {
      "type": "string",
      "description": "URL from where information about model development can be obtained"
    },
    "model_version": {
      "type": "string",
      "description": "version of the model file"
    },
    "frog_id": {
      "type": "string",
      "description": "identifier of the FROG report unique within a repository"
    },
    "environment": {
      "type": "string",
      "description": "free-text description of software environment used to generate the environment, such as the operating system"
    },
    "software": {
      "type": "object",
      "description": "description of individual software components used to generate the report",
      "patternProperties": {
        "^.*$": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "name of the software"
            },
            "version": {
              "type": "string",
              "description": "version of the software"
            },
            "url": {
              "type": "string",
              "description": "URL from where the software can be obtained"
            },
            "configuration": {
              "type": "object",
              "description": "free-form description of configuration options and values used to set up the software, such as solver parameters"
            }
          },
          "additionalProperties": false,
          "required": [
            "name",
            "version"
          ]
        }
      },
      "required": [
        "frog",
        "solver"
      ]
    },
    "additionalProperties": false
  },
  "additionalProperties": false,
  "required": [
    "frog_version",
    "model_filename",
    "model_md5",
    "software",
    "environment"
  ]
}

=== LCSB-BioCore/frog-specification/data/ecoli/metadata.json
{
  "frog_version": "0.0.2",
  "frog_id": "e_coli_core.xml-cobrapy-glpk",
  "model_filename": "e_coli_core.xml",
  "model_md5": "4574760460afe9e1b3388dc15f354706",
  "model_sha256": "b4db506aeed0e434c1f5f1fdd35feda0dfe5d82badcfda0e9d1342335ab31116",
  "software": {
    "frog": {
      "name": "fbc_curation",
      "version": "0.2.2",
      "url": "https://doi.org/10.5281/zenodo.3708271"
    },
    "cobra": {
      "name": "cobrapy",
      "version": "0.26.0",
      "url": "https://github.com/opencobra/cobrapy"
    },
    "solver": {
      "name": "GLPK",
      "version": "1.0.1",
      "configuration": {
        "tm_lim": 60000
      }
    }
  },
  "environment": "posix, Linux, 5.15.0-53-generic"
}
